### PR TITLE
Dev/activities

### PR DESCRIPTION
**Pull request by michaelaird**
Adding Activities to the CharacterResponse. 
Also adding a standard .gitignore

### CODE REVIEW

**Review by andyschott — APPROVED** [review]
Thanks for the contribution! I'll get a new release published shortly - it should be version `1.11.0`.

**Comment by michaelaird** [comment]
Thanks! I'm probably going to have couple more PRs shortly. I'm playing around with "upgrading" the recommendation engine in https://github.com/andyschott/MaxPowerLevel to take into account what activities the player has already completed each week.

**Comment by andyschott** [comment]
I've thought about doing that, but have decided against it so far. I like the idea in theory, but the problem is the activities API isn't consistent between activities, and it can be very complicated to determine if a character has done that activity yet this week.

**Comment by michaelaird** [comment]
I think I have it 90% working based on Milestone information. The only bit I haven't figured out for this season is Presage completions. 

I'll put up a draft PR for you review shortly.

**Pull request merged**
